# Generated by Django 5.2.5 on 2025-08-21 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_corto', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'constraints': [models.UniqueConstraint(fields=('nombre',), name='unique_nombre_oficina'), models.UniqueConstraint(fields=('nombre_corto',), name='unique_nombre_corto_oficina')],
            },
        ),
    ]
