# Generated by Django 5.2.5 on 2025-08-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oficina',
            options={'verbose_name': 'Oficina', 'verbose_name_plural': 'Oficinas'},
        ),
        migrations.AlterField(
            model_name='oficina',
            name='nombre_corto',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='oficina',
            constraint=models.UniqueConstraint(fields=('nombre',), name='unique_nombre_oficina'),
        ),
        migrations.AddConstraint(
            model_name='oficina',
            constraint=models.UniqueConstraint(fields=('nombre_corto',), name='unique_nombre_corto_oficina'),
        ),
    ]
