# Generated by Django 5.2.5 on 2025-08-21 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_alter_oficina_options_alter_oficina_nombre_corto_and_more'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='oficina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='oficina.oficina'),
        ),
    ]
